

export default [
    {
        id: "1",
        Nombre: "Cándido",
        Especie: "Gato",
        Raza: "Siamés",
        Tamaño: "Mediano",
        Sexo: "Macho",
        Años: "7",
        Meses: "5",
        Chip: "",
        Placa: "",
        Cola: "Cola larga",
        Orejas: "Orejas paradas",
        Color: "Cafe Claro",
        Manchas: "Cafe Claro",
        Observaciones: "Carita, patas, cola color chocolate. Ojos azules",
        foto1: "lili.png",
        foto2: "",
        foto3: "",
        fecha: "21/08/2022",
        nombreDueño: "Jose Francisco Revuelta Meza",
        telefonoDueño: "4423599847",
        mailDueño: "jofrarem@hotmail.com"

        /*id: "1",
        nombre: "Lili",
        color: "blanca",
        sexo: "hembra",
        raza: "caniche",
        años: "12",
        meses: "5",
        chip: "522011",
        orejas: "puntiagudas",
        observaciones: "Se perdió después de una explosión e incendio en el edificio que se encuentra sobre Tlalpan, casi esquina con Xola, necesitamos llevarlo al veterinario estaba en tratamiento por problemas pulmonares, y es muy probable que se haya afectado por la explosión, la última vez que se vio fue en el elevador del edificio, es pequeño, tiene correa roja.",
        foto1: "lili.png",
        foto2: "",
        foto3: "",
        fecha: "12/05/2020",
        nombreDueño: "Alvaro Salazar",
        telefonoDueño: "381764422",
        mailDueño: "alvarosalazar@gmail.com"
        */
    },
    {
        id: "2",
        nombre: "Lili",
        color: "blanca",
        sexo: "hembra",
        raza: "caniche",
        años: "12",
        meses: "5",
        chip: "522011",
        orejas: "puntiagudas",
        observaciones: "Se perdió después de una explosión e incendio en el edificio que se encuentra sobre Tlalpan, casi esquina con Xola, necesitamos llevarlo al veterinario estaba en tratamiento por problemas pulmonares, y es muy probable que se haya afectado por la explosión, la última vez que se vio fue en el elevador del edificio, es pequeño, tiene correa roja.",
        foto1: "lili.png",
        foto2: "",
        foto3: "",
        fecha: "12/05/2020",
        nombreDueño: "Alvaro Salazar",
        telefonoDueño: "381764422",
        mailDueño: "alvarosalazar@gmail.com"
        
    },
    {
        id: "3",
        nombre: "Lili",
        color: "blanca",
        sexo: "hembra",
        raza: "caniche",
        años: "12",
        meses: "5",
        chip: "522011",
        orejas: "puntiagudas",
        observaciones: "Se perdió después de una explosión e incendio en el edificio que se encuentra sobre Tlalpan, casi esquina con Xola, necesitamos llevarlo al veterinario estaba en tratamiento por problemas pulmonares, y es muy probable que se haya afectado por la explosión, la última vez que se vio fue en el elevador del edificio, es pequeño, tiene correa roja.",
        foto1: "lili.png",
        foto2: "",
        foto3: "",
        fecha: "12/05/2020",
        nombreDueño: "Alvaro Salazar",
        telefonoDueño: "381764422",
        mailDueño: "alvarosalazar@gmail.com"
        
    }
]