

// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        id: "1",
        nombre: "Cándido",
        especie: "Gato",
        raza: "Siamés",
        tamaño: "Mediano",
        sexo: "Macho",
        años: "7",
        meses: "5",
        chip: "",
        placa: "",
        cola: "Cola larga",
        orejas: "Orejas paradas",
        color: "Cafe Claro",
        manchas: "Cafe Claro",
        observaciones: "Carita, patas, cola color chocolate. Ojos azules",
        foto1: "candido.jpg",
        foto2: "",
        foto3: "",
        fecha: "21/08/2022",
        nombreDueño: "Jose Francisco Revuelta Meza",
        telefonoDueño: "4423599847",
        mailDueño: "jofrarem@hotmail.com"

    },
    {
        id: "2",
        nombre: "Olivia",
        especie: "Perro",
        raza: "Boxer",
        tamaño: "Grande",
        sexo: "Hembra",
        años: "3",
        meses: "5",
        chip: "",
        placa: "",
        cola: "Cola larga",
        orejas: "Orejas caídas",
        color: "Cafe Obscuro",
        manchas: "Cafe Claro",
        observaciones: "Busco a Olivia. Es una perrita café tipo Bóxer. Es un poco miedosa, pero sí te le acercas lento y llamándola por su nombre atiende y busca la caricia. No tiene placa ni collar. Ayuda por favor!",
        foto1: "olivia.jpg",
        foto2: "",
        foto3: "",
        fecha: "21/08/2022",
        nombreDueño: "Paul Ohea Flores",
        telefonoDueño: "5547955571",
        mailDueño: "sofia.delnor@gmail.com"
        
    },
   {
    id: "3",
    nombre: "Olivia",
    especie: "Perro",
    raza: "Boxer",
    tamaño: "Grande",
    sexo: "Hembra",
    años: "3",
    meses: "5",
    chip: "",
    placa: "",
    cola: "Cola larga",
    orejas: "Orejas caídas",
    color: "Cafe Obscuro",
    manchas: "Cafe Claro",
    observaciones: "Busco a Olivia. Es una perrita café tipo Bóxer. Es un poco miedosa, pero sí te le acercas lento y llamándola por su nombre atiende y busca la caricia. No tiene placa ni collar. Ayuda por favor!",
    foto1: "olivia.jpg",
    foto2: "",
    foto3: "",
    fecha: "21/08/2022",
    nombreDueño: "Paul Ohea Flores",
    telefonoDueño: "5547955571",
    mailDueño: "sofia.delnor@gmail.com"
   },
   {
    id: "4",
        nombre: "Bandido",
        especie: "Perro",
        raza: "Única/Mix/Sin Raza",
        tamaño: "Chico",
        sexo: "Macho",
        años: "5",
        meses: "",
        chip: "",
        placa: "",
        cola: "Cola larga",
        orejas: "Orejas caídas",
        color: "Negr",
        manchas: "Blanco",
        observaciones: "Se perdió en Tafi Viejo ,Tiene pecho blanco , es cariñoso y juguetón , no muerte es pequeñito , le gusta estar en los parques y tiene mucho cabello",
        foto1: "Bandido.jpeg",
        foto2: "",
        foto3: "",
        fecha: "02/08/2022",
        nombreDueño: "Maria",
        telefonoDueño: "938523023",
        mailDueño: "nataliacalinares@gmail.com",
        lugar: "Avenida alem 330, tafi viejo"
   },
   {
    id: "5",
        nombre: "Canelo",
        especie: "Perro",
        raza: "Única/Mix/Sin Raza",
        tamaño: "Grande",
        sexo: "Macho",
        años: "4",
        meses: "",
        chip: "",
        placa: "",
        cola: "Cola larga",
        orejas: "Orejas paradas",
        color: "Cafe claro",
        manchas: "",
        observaciones: "Color amarillo o dorado, con sus patas delanteras color blanco y con una raya centrada color blanco que comienza en su cabecita y que termina hasta su frente.",
        foto1: "canelo.png",
        foto2: "",
        foto3: "",
        fecha: "03/04/2022",
        nombreDueño: "Alejandro M.",
        telefonoDueño: "735 277 3566",
        mailDueño: "moctezumaalejandro25@gmail.com",
        lugar: "Perdido en Avenida Salta altura 576, S.M Tucuman"
   },
   {
    id: "6",
        nombre: "MITZY",
        especie: "Perro",
        raza: "Única/Mix/Sin Raza",
        tamaño: "Mediano",
        sexo: "Hembra",
        años: "2",
        meses: "4",
        chip: "",
        placa: "",
        cola: "Cola larga",
        orejas: "Orejas paradas",
        color: "Gris",
        manchas: "Blanco",
        observaciones: "Busco perrita husky, responde a nombre de mitzi salio entre 10- 10:30 pm, por la terminal de omnibus !!!!! Por favor solo quiero que vuelva a casa",
        foto1: "mitzy.jpg",
        foto2: "",
        foto3: "",
        fecha: "09/06/2022",
        nombreDueño: "Mariana Navarro Reyna",
        telefonoDueño: "+52 97 11561576",
        mailDueño: "navarroyai21@gmail.com",
        lugar: "Perdido en terminal de omnibus nueva, S.M Tucuman"
   },
   {
    id: "7",
        nombre: "cati",
        especie: "Perro",
        raza: "Única/Mix/Sin Raza",
        tamaño: "Chico",
        sexo: "Hembra",
        años: "10",
        meses: "",
        chip: "",
        placa: "",
        cola: "Cola larga",
        orejas: "Orejas caidas",
        color: "Blanco",
        manchas: "Blanco",
        observaciones: "se extravió el sábado 11 de junio de 2022 por la tarde noche",
        foto1: "cati.jpeg",
        foto2: "",
        foto3: "",
        fecha: "11/06/2022",
        nombreDueño: "Rocio",
        telefonoDueño: "2214132232",
        mailDueño: "chiosilva2003@yahoo.com.mx",
        lugar: "Laprida 55, frente plaza independencia, S.M Tucuman"
   },    
   {
    id: "8",
        nombre: "cati",
        especie: "Perro",
        raza: "Única/Mix/Sin Raza",
        tamaño: "Chico",
        sexo: "Hembra",
        años: "10",
        meses: "",
        chip: "",
        placa: "",
        cola: "Cola larga",
        orejas: "Orejas caidas",
        color: "Blanco",
        manchas: "Blanco",
        observaciones: "se extravió el sábado 11 de junio de 2022 por la tarde noche",
        foto1: "cati.jpeg",
        foto2: "",
        foto3: "",
        fecha: "11/06/2022",
        nombreDueño: "Rocio",
        telefonoDueño: "2214132232",
        mailDueño: "chiosilva2003@yahoo.com.mx",
        lugar: "Laprida 55, frente plaza independencia, S.M Tucuman"
   }
]